// Generated by gencpp from file lab_e_traffic_bot/Traffic.msg
// DO NOT EDIT!


#ifndef LAB_E_TRAFFIC_BOT_MESSAGE_TRAFFIC_H
#define LAB_E_TRAFFIC_BOT_MESSAGE_TRAFFIC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab_e_traffic_bot
{
template <class ContainerAllocator>
struct Traffic_
{
  typedef Traffic_<ContainerAllocator> Type;

  Traffic_()
    {
    }
  Traffic_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> const> ConstPtr;

}; // struct Traffic_

typedef ::lab_e_traffic_bot::Traffic_<std::allocator<void> > Traffic;

typedef boost::shared_ptr< ::lab_e_traffic_bot::Traffic > TrafficPtr;
typedef boost::shared_ptr< ::lab_e_traffic_bot::Traffic const> TrafficConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab_e_traffic_bot::Traffic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace lab_e_traffic_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::lab_e_traffic_bot::Traffic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab_e_traffic_bot/Traffic";
  }

  static const char* value(const ::lab_e_traffic_bot::Traffic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#TODO: Define what your custom message includes here\n"
"#Here's a list of built-in primitive types: http://wiki.ros.org/msg\n"
;
  }

  static const char* value(const ::lab_e_traffic_bot::Traffic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Traffic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab_e_traffic_bot::Traffic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::lab_e_traffic_bot::Traffic_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LAB_E_TRAFFIC_BOT_MESSAGE_TRAFFIC_H
